### ISSUE TITLE
NTU datasets

### ISSUE THREAD

**Issue by sheshap** [XingLi1012/SequentialPointNet#1]
Dear Authors,

Thank you so much for releasing the code. Much appreciated.

I have access to the NTU dataset. However, I see the size of the dataset varies between 83GBs to 886GBs.
Can you please help me understand which among the below to use and if any pre-processing script was used for the dataset?

1.2 "NTU RGB+D" -Masked Depth Maps -- 83GB
1.3 "NTU RGB+D" - Full Depth Maps -- 886GB
1.4 "NTU RGB+D" - RGB Videos -- 136GB
1.5 "NTU RGB+D" - IR Videos -- 221GB

2.2 "NTU RGB+D 120" - Masked Depth Maps -- 83+64
2.3 "NTU RGB+D 120" - Full Depth Maps
2.4 "NTU RGB+D 120" - RGB videos -- 136+124
2.5 "NTU RGB+D 120" - IR videos -- 221+168

I find the MSRAction3D dataset is pretty straightforward.

Thanks in Advance.

**Comment by XingLi1012** [comment]
Dear&nbsp;Shivanand Venkanna Sheshappanavar&nbsp;,
I am glad to answer your question.
In NTU dataset, the 1.2 "NTU RGB+D" -Masked Depth Maps -- 83GB&nbsp; and 2.2 "NTU RGB+D 120" - Masked Depth Maps -- 83+64 are used in our paper.
No pre-processing script was used for the dataset.
Only need to decompress each database file.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XingLi1012/SequentialPointNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 中午1:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XingLi1012/SequentialPointNet] NTU datasets (Issue #1)





 
Dear Authors,
 
Thank you so much for releasing the code. Much appreciated.
 
I have access to the NTU dataset. However, I see the size of the dataset varies between 83GBs to 886GBs.
 Can you please help me understand which among the below to use and if any pre-processing script was used for the dataset?
 
1.2 "NTU RGB+D" -Masked Depth Maps -- 83GB
 1.3 "NTU RGB+D" - Full Depth Maps -- 886GB
 1.4 "NTU RGB+D" - RGB Videos -- 136GB
 1.5 "NTU RGB+D" - IR Videos -- 221GB
 
2.2 "NTU RGB+D 120" - Masked Depth Maps -- 83+64
 2.3 "NTU RGB+D 120" - Full Depth Maps
 2.4 "NTU RGB+D 120" - RGB videos -- 136+124
 2.5 "NTU RGB+D 120" - IR videos -- 221+168
 
I find the MSRAction3D dataset is pretty straightforward.
 
Thanks in Advance.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sheshap** [comment]
Thank you so much for your reply.
